### import numpy

In [1]:
import numpy as np

### check python and numpy version

In [2]:
import platform
print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)

Python version: 3.10.12
Numpy version: 1.26.4


# 0. Numpy Data Types

### A list of Numpy Data Types

In [7]:
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

In [9]:
# create an array with a specified data type
arr = np.array([1,2,3], dtype='f8')
print(arr)
print(arr.dtype)

arr = np.array([1+2j, 3-4j], dtype="complex64")
print(arr)
print(arr.dtype)

arr = np.array([0, 1, 1], dtype="bool")
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64
[1.+2.j 3.-4.j]
complex64
[False  True  True]
bool


### string data type

In [10]:
# set the max length of the string using S + some number, such as 'S3'
# any string longer than the max length will be truncated
s = np.array(['abc', 'defg'], dtype='S3')
print(s)
print(s.dtype)

[b'abc' b'def']
|S3


# 1. Create Arrays

### create an array from a Python array

In [11]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### create an array in a specified data type

In [13]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


### create an aray of evenly spaced values within a specified interval

In [14]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### create an array of evenly spaced numbers in a specified interval

In [ ]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)

"""
Parameters:
start:
  The starting value of the sequence.
stop:
  The end value of the sequence. This value is included in the output if endpoint=True (the default).

num_of_elements:
  The number of evenly spaced samples to generate. This is an integer value that specifies how many values to include between start and stop.

endpoint:
  A boolean value (default is True).
  If True, stop is the last value in the sequence. If False, the sequence ends before stop.

retstep:
  A boolean value (default is False).
  If True, the function returns a tuple with the array of values and the step size between values.
  """
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [15]:
# exclude endpoint and return setp size
arr, step = np.linspace(0, 10, 20, endpoint=False, retstep=True)
print(arr)
print(step)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
0.5


### create an array of random values in a given shape

In [16]:
arr = np.random.rand(3, 3)
print(arr)

[[0.01996959 0.99926209 0.65039642]
 [0.89971804 0.09000168 0.8837737 ]
 [0.74689476 0.62877156 0.8082318 ]]


### create an array of zeros in a given shape

In [17]:
zeros = np.zeros((2,3), dtype='i4')
print(zeros)

[[0 0 0]
 [0 0 0]]


### create an array of zeros with the same shape and data type as a given array

In [18]:
zeros = np.zeros_like(arr)
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### create an array of ones in a given shape

In [19]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of ones with the same shape and data type as a given array

In [20]:
ones = np.ones_like(arr)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### create an array of arbitrary values in a given shape

In [21]:
empty = np.empty((2,3))
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of arbitrary values with the same shape and data type as a given array

In [22]:
empty = np.empty_like(arr)
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### create an array of constant values in a given shape  

In [23]:
p = np.full((2,3), 5)
print(p)

[[5 5 5]
 [5 5 5]]


### create an array of constant values with the same shape and data type as a given array

In [24]:
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### create an array by repetition

In [31]:
# repeat each element of an array by a specified number of times
# np.repeat(iterable, reps, axis=None)
arr = [0, 1, 2]
print(np.repeat(arr, 3))    # or np.repeat(range(3), 3)

[0 0 0 1 1 1 2 2 2]


In [36]:
# repeat along a specified axis with specified number of repetitions
arr = [[1,2], [3,4], [6,5]]
print(np.repeat(arr, [1,2,3], axis=0))

[[1 2]
 [3 4]
 [3 4]
 [6 5]
 [6 5]
 [6 5]]


In [37]:
# repeat an array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [38]:
# repeat along specified axes
print(np.tile(arr, (2,3)))

[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


### create an identity matrix with a given diagonal size

In [39]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
# Create a 3x4 matrix with ones on the main diagonal
eye_matrix = np.eye(3, 4)
print(eye_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [40]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### create an identity matrix with a diagonal offset

In [42]:
identity_matrix = np.eye(5, k=1)    # positive number shifts the diagonal upward
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [43]:
identity_matrix = np.eye(5, k=-2)   # negative number shifts the diagonal downward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### extract the diagonal array / create a diagonal array

In [44]:
arr = np.random.rand(5,5)
print(arr)

[[0.15108479 0.30063728 0.38282016 0.19254983 0.77364159]
 [0.5739463  0.59060596 0.65072608 0.0921168  0.63252727]
 [0.87102904 0.86527627 0.49220555 0.42403043 0.42073796]
 [0.91718417 0.50322167 0.50338281 0.28360764 0.2585825 ]
 [0.60024569 0.52543555 0.98792247 0.56324477 0.36619883]]


In [45]:
# extract the diagonal
print(np.diag(arr))

[0.15108479 0.59060596 0.49220555 0.28360764 0.36619883]


In [46]:
# create a matrix with a specified diagonal array
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 2. Inspect Arrays

In [47]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

### inspect the data type of an array

In [49]:
print(arr.dtype)

int64


### inspect the dimension of an array

In [50]:
print(arr.shape)

(2, 3)


### inspect length of an array

In [51]:
print(len(arr))

2


### inspect the number of dimensions of an array

In [52]:
print(arr.ndim)

2


### inspect the number of elements in an array

In [53]:
print(arr.size)

6


### inspect the number of bytes of each element in an array

In [54]:
print(arr.itemsize)

8


### inspect the memory size of an array (in byte)

In [55]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


# 3. Sampling Methods

### generate a random sample from interval [0, 1) in a given shape

In [74]:
# generate a random scalar
print(np.random.rand())

0.5513147690828912


In [75]:
# generate a 1-D array
print(np.random.rand(3))

[0.71946897 0.42310646 0.9807642 ]


In [76]:
# generate a 2-D array
print(np.random.rand(3,3))

[[0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]
 [0.0596779  0.39804426 0.73799541]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [77]:
print(np.random.randn(3,3))

[[-0.44398196 -0.43435128  2.20593008]
 [ 2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387]]


### generate an array of random integers in a given interval [low, high)

In [79]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i4'))

[9 4 6]


In [80]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[1 3 7]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [81]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.42583029 0.31226122 0.42635131 0.89338916 0.94416002 0.50183668
 0.62395295 0.1156184  0.31728548 0.41482621]
[0.86630916 0.25045537 0.48303426 0.98555979 0.51948512 0.61289453
 0.12062867 0.8263408  0.60306013 0.54506801]
[0.34276383 0.30412079 0.41702221 0.68130077 0.87545684 0.51042234
 0.66931378 0.58593655 0.6249035  0.67468905]
[0.84234244 0.08319499 0.76368284 0.24366637 0.19422296 0.57245696
 0.09571252 0.88532683 0.62724897 0.72341636]


### generate a random sample from a given 1-D array

In [82]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[0 1 1 1 1 1 1 1 1 1]


In [83]:
print(np.random.choice(3, 10))

[2 1 2 0 1 0 2 0 0 2]


In [84]:
print(np.random.choice([1,2,3], 10))

[1 3 2 1 1 1 1 1 1 2]


### shuffle an array in place

In [85]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [87]:
np.random.shuffle(arr)
print(arr)

[7 5 8 1 6 0 3 4 9 2]


### generate a permutation of an array

In [89]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [5 4 2 0 6 3 1 9 7 8]


# 4. Math Functions

In [90]:
arr = np.random.rand(5,5)

### element-wise addition, subtraction, multiplication and division

In [91]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.52153306 10.00268806 10.98834542 10.90534158 10.20763586]
 [10.29248941 10.52001015 10.90191137 10.98363088 10.25754206]
 [10.56435904 10.80696868 10.39437005 10.73107304 10.16106901]
 [10.60069857 10.86586446 10.98352161 10.07936579 10.42834727]
 [10.20454286 10.45063649 10.54776357 10.09332671 10.29686078]]
[[-9.47846694 -9.99731194 -9.01165458 -9.09465842 -9.79236414]
 [-9.70751059 -9.47998985 -9.09808863 -9.01636912 -9.74245794]
 [-9.43564096 -9.19303132 -9.60562995 -9.26892696 -9.83893099]
 [-9.39930143 -9.13413554 -9.01647839 -9.92063421 -9.57165273]
 [-9.79545714 -9.54936351 -9.45223643 -9.90667329 -9.70313922]]
[[5.21533059 0.02688065 9.88345419 9.05341576 2.07635861]
 [2.92489413 5.20010153 9.01911373 9.83630885 2.57542064]
 [5.64359043 8.06968684 3.94370054 7.31073036 1.61069014]
 [6.00698568 8.65864458 9.83521609 0.7936579  4.28347275]
 [2.0454286  4.50636491 5.47763573 0.9332671  2.96860775]]
[[0.05215331 0.00026881 0.09883454 0.09053416 0.02076359]
 [0.02924894 0.0520

In [93]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

In [94]:
print(np.exp(arr))

[[1.68460828 1.00269168 2.68678529 2.47277642 1.23076492]
 [1.33975855 1.68204473 2.46430883 2.67414816 1.29374623]
 [1.75832041 2.24110418 1.4834494  2.07730844 1.17476604]
 [1.82339212 2.37706007 2.67385596 1.08260025 1.53471896]
 [1.22696404 1.56931072 1.72938105 1.09782035 1.34562794]]


### element-wise logorithm

In [95]:
# natural log
print(np.log(arr))

[[-0.65098261 -5.91893383 -0.01172303 -0.09944297 -1.5719694 ]
 [-1.22932681 -0.65390694 -0.10323902 -0.01650457 -1.35657222]
 [-0.57206463 -0.21447042 -0.93046559 -0.31324191 -1.82592234]
 [-0.50966202 -0.1440269  -0.01661567 -2.53368786 -0.84782102]
 [-1.58697774 -0.79709427 -0.60191152 -2.37164893 -1.21449202]]


In [96]:
# base 2
print(np.log2(arr))

[[-0.93916939 -8.53921649 -0.01691275 -0.14346589 -2.26787246]
 [-1.77354369 -0.9433883  -0.14894242 -0.02381106 -1.95712001]
 [-0.8253148  -0.30941541 -1.34237809 -0.45191255 -2.63424911]
 [-0.73528687 -0.20778689 -0.02397134 -3.6553389  -1.22314719]
 [-2.28952492 -1.14996395 -0.86837477 -3.42156615 -1.75214161]]


In [97]:
# base 10
print(np.log10(arr))

[[-0.28271816 -2.5705603  -0.00509125 -0.04318754 -0.68269764]
 [-0.53388985 -0.28398818 -0.04483614 -0.00716784 -0.58915183]
 [-0.24844451 -0.09314332 -0.40409607 -0.13603923 -0.792988  ]
 [-0.2213434  -0.06255009 -0.00721609 -1.10036665 -0.36820399]
 [-0.68921568 -0.34617364 -0.26140685 -1.02999404 -0.52744718]]


### element-wise square root

In [98]:
print(np.sqrt(arr))

[[0.72217246 0.05184655 0.99415563 0.95149439 0.45567078]
 [0.5408229  0.72111729 0.94969015 0.99178167 0.50748602]
 [0.75123834 0.89831436 0.6279889  0.85502809 0.40133404]
 [0.77504746 0.93051838 0.99172658 0.28171935 0.65448245]
 [0.45226415 0.67129464 0.74011051 0.30549421 0.54484931]]


### element-wise sine and cosine

In [101]:
print(np.sin(arr))

[[0.49820997 0.00268806 0.83511698 0.7866361  0.20614712]
 [0.2883368  0.49688895 0.78451361 0.83251438 0.25470445]
 [0.53487436 0.72219376 0.38422667 0.66766885 0.16037348]
 [0.56521889 0.7616557  0.83245383 0.0792825  0.41536796]
 [0.20311957 0.43553857 0.52077931 0.09319129 0.29251974]]


In [102]:
print(np.cos(arr))

[[0.86705641 0.99999639 0.55007238 0.61741692 0.97852101]
 [0.95752905 0.86781413 0.6201116  0.55400344 0.96701895]
 [0.84493161 0.6916908  0.92323879 0.7444584  0.98705641]
 [0.82494097 0.64798194 0.55409441 0.99685219 0.90965348]
 [0.97915394 0.90017007 0.85369134 0.99564822 0.95625948]]


### sum along a specified axis

In [103]:
# sum along the row
print(np.sum(arr, axis=0))

[2.18362294 2.64616785 3.81591203 2.792738   1.35145499]


In [104]:
# sum along the column
print(np.sum(arr, axis=1))

[2.62554398 2.95558389 2.65783983 2.9577977  1.59313041]


### compute the min and max along a specified axis

In [105]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.20454286 0.00268806 0.39437005 0.07936579 0.16106901]


In [106]:
# calculate max along the column
print(np.max(arr, axis=1))

[0.98834542 0.98363088 0.80696868 0.98352161 0.54776357]


In [107]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.98834541928282
0.002688064574320692


### compute the indices of the min and max along a specified axis

In [108]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[4 0 2 3 2]
[3 3 0 1 3]


In [109]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[1 4 4 3 3]
[2 3 1 2 2]


In [110]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

1
2


### compute element-wise min and max of two arrays

In [111]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [112]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.2758424  0.69003731 0.57411998 0.53525991 0.41862152 0.48579033
 0.08697395 0.39243348 0.65937884 0.80997938]
integral:  [9. 5. 4. 7. 7. 0. 7. 8. 1. 7.]


### compute the mean

In [113]:
# compute the overall mean
print(np.mean(arr))

0.5115958323182477


In [114]:
# compute the mean along the row
print(np.mean(arr, axis=0))

[0.43672459 0.52923357 0.76318241 0.5585476  0.270291  ]


In [115]:
# compute the mean along the column
print(np.mean(arr, axis=1))

[0.5251088  0.59111678 0.53156797 0.59155954 0.31862608]


### compute the median

In [116]:
# compute the overall median
print(np.median(arr))

0.5200101530724834


In [117]:
# compute the median along the row
print(np.median(arr, axis=0))

[0.52153306 0.52001015 0.90191137 0.73107304 0.25754206]


In [118]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.52153306 0.52001015 0.56435904 0.60069857 0.29686078]


### compute the percentile

In [119]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.0471337  0.65609592 0.93348576]


### compute the standard deviation & variance

In [120]:
# compute the overall standard deviation
print(np.std(arr))

0.30768017288784044


In [121]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.15816614 0.30788631 0.2453248  0.39415037 0.09132949]


In [122]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.38285517 0.30204872 0.2335876  0.32185141 0.16381652]


In [123]:
# compute the overall variance
print(np.var(arr))

0.09466708878829139


In [124]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.02501653 0.09479398 0.06018426 0.15535451 0.00834108]


In [125]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.14657808 0.09123343 0.05456316 0.10358833 0.02683585]


### compute the covariance & correlation

In [126]:
arr = np.random.rand(5,8)

In [127]:
print(np.cov(arr))

[[ 0.11477884 -0.01362451 -0.01384715 -0.03160288  0.00554565]
 [-0.01362451  0.08876364 -0.02404343  0.04854743  0.00897158]
 [-0.01384715 -0.02404343  0.03900587 -0.05036849 -0.00903842]
 [-0.03160288  0.04854743 -0.05036849  0.12040291 -0.01233354]
 [ 0.00554565  0.00897158 -0.00903842 -0.01233354  0.10008976]]


In [129]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.68686813]
 [-0.68686813  1.        ]]


### compute cumulative sum & product

In [131]:
arr

array([[0.71560128, 0.41051979, 0.19100696, 0.96749431, 0.65075037,
        0.86545985, 0.02524236, 0.26690581],
       [0.5020711 , 0.06744864, 0.99303326, 0.2364624 , 0.37429218,
        0.21401191, 0.10544587, 0.23247979],
       [0.30061014, 0.63444227, 0.28123478, 0.36227676, 0.00594284,
        0.36571913, 0.53388598, 0.16201584],
       [0.59743311, 0.29315247, 0.63205049, 0.02619661, 0.88759346,
        0.01611863, 0.12695803, 0.77716246],
       [0.04589523, 0.71099869, 0.97104614, 0.87168293, 0.71016165,
        0.95850974, 0.42981334, 0.87287891]])

### element-wise comparison

In [134]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [135]:
# return an array of bools
print(arr1 == arr2)
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


# 5. Slicing & Indexing

In [144]:
arr = np.array(range(100)).reshape((10,10))

In [145]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### select an element by row and column indices

In [146]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [147]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [149]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [150]:
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

### assign a scalar to a slice by broadcasting

In [151]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


### boolean indexing

In [152]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [153]:
# negate the condition
print(arr1[~bools])

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [154]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [155]:
arr = np.random.rand(10,10)

In [156]:
arr

array([[0.35595767, 0.92976365, 0.14877766, 0.94002901, 0.8327162 ,
        0.84605484, 0.12392301, 0.5964869 , 0.01639248, 0.72118437],
       [0.00773751, 0.08482228, 0.22549841, 0.87512453, 0.36357632,
        0.53995994, 0.56810321, 0.22546336, 0.57214677, 0.6609518 ],
       [0.29824539, 0.41862686, 0.45308892, 0.93235066, 0.58749375,
        0.94825237, 0.55603475, 0.50056142, 0.00353221, 0.48088904],
       [0.927455  , 0.19836569, 0.05209113, 0.40677889, 0.37239648,
        0.85715306, 0.02661112, 0.92014923, 0.680903  , 0.90422599],
       [0.60752907, 0.81195331, 0.33554387, 0.34956623, 0.38987423,
        0.75479708, 0.36929117, 0.24221981, 0.93766836, 0.90801108],
       [0.34879732, 0.63463807, 0.27384221, 0.20611513, 0.33633953,
        0.32709989, 0.8822761 , 0.82230381, 0.70962323, 0.95934523],
       [0.42254335, 0.24503304, 0.11739844, 0.30105336, 0.14526373,
        0.0921861 , 0.6029322 , 0.36418745, 0.56457034, 0.19133572],
       [0.67690586, 0.21550545, 0.2780235

In [159]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])

[0.40677889 0.22549841 0.41862686]


In [160]:
arr[[3,1,2]]

array([[0.927455  , 0.19836569, 0.05209113, 0.40677889, 0.37239648,
        0.85715306, 0.02661112, 0.92014923, 0.680903  , 0.90422599],
       [0.00773751, 0.08482228, 0.22549841, 0.87512453, 0.36357632,
        0.53995994, 0.56810321, 0.22546336, 0.57214677, 0.6609518 ],
       [0.29824539, 0.41862686, 0.45308892, 0.93235066, 0.58749375,
        0.94825237, 0.55603475, 0.50056142, 0.00353221, 0.48088904]])

In [161]:
# select rows 3,1,2 and columns 6,4,8
print(arr[[3,1,2]][:, [6,4,8]])

[[0.02661112 0.37239648 0.680903  ]
 [0.56810321 0.36357632 0.57214677]
 [0.55603475 0.58749375 0.00353221]]


### dimension inference

In [162]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [163]:
arr = np.arange(16).reshape(4,4)

In [170]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [164]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [167]:
arr[np.where(arr>5)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [168]:
# return values based on conditions
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [171]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


# 6. Sort an Array

In [172]:
arr = np.random.rand(5,5)

In [174]:
arr

array([[0.94436554, 0.49119048, 0.27017627, 0.36042372, 0.21065263],
       [0.42120006, 0.21803544, 0.84575251, 0.4562706 , 0.27980202],
       [0.93289165, 0.31435135, 0.90971466, 0.04341809, 0.70711506],
       [0.48388904, 0.44422106, 0.03632334, 0.04068319, 0.33275362],
       [0.94711954, 0.61765998, 0.36887484, 0.61197704, 0.20613154]])

### sort an array along a specified axis

In [175]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))

[[0.42120006 0.21803544 0.03632334 0.04068319 0.20613154]
 [0.48388904 0.31435135 0.27017627 0.04341809 0.21065263]
 [0.93289165 0.44422106 0.36887484 0.36042372 0.27980202]
 [0.94436554 0.49119048 0.84575251 0.4562706  0.33275362]
 [0.94711954 0.61765998 0.90971466 0.61197704 0.70711506]]


In [176]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.42120006 0.21803544 0.03632334 0.04068319 0.20613154]
 [0.48388904 0.31435135 0.27017627 0.04341809 0.21065263]
 [0.93289165 0.44422106 0.36887484 0.36042372 0.27980202]
 [0.94436554 0.49119048 0.84575251 0.4562706  0.33275362]
 [0.94711954 0.61765998 0.90971466 0.61197704 0.70711506]]


In [177]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))

[[0.03632334 0.04068319 0.20613154 0.21803544 0.42120006]
 [0.04341809 0.21065263 0.27017627 0.31435135 0.48388904]
 [0.27980202 0.36042372 0.36887484 0.44422106 0.93289165]
 [0.33275362 0.4562706  0.49119048 0.84575251 0.94436554]
 [0.61197704 0.61765998 0.70711506 0.90971466 0.94711954]]


In [178]:
# sort along the column in place
arr.sort(axis=1)
print(arr)

[[0.03632334 0.04068319 0.20613154 0.21803544 0.42120006]
 [0.04341809 0.21065263 0.27017627 0.31435135 0.48388904]
 [0.27980202 0.36042372 0.36887484 0.44422106 0.93289165]
 [0.33275362 0.4562706  0.49119048 0.84575251 0.94436554]
 [0.61197704 0.61765998 0.70711506 0.90971466 0.94711954]]


### compute the indices that would sort an array along a specified axis

In [180]:
arr = np.random.rand(5,5)
arr

array([[0.86831471, 0.28047698, 0.02057616, 0.91809702, 0.86448028],
       [0.27690179, 0.52348755, 0.1090882 , 0.09342707, 0.83746611],
       [0.41026572, 0.66171654, 0.94320056, 0.24513059, 0.01315983],
       [0.02414841, 0.70938569, 0.92455188, 0.46733027, 0.37510915],
       [0.54286042, 0.85891684, 0.65215387, 0.2329799 , 0.7745802 ]])

In [181]:
# along the row
print(np.argsort(arr, axis=0))

[[3 0 0 1 2]
 [1 1 1 4 3]
 [2 2 4 2 4]
 [4 3 3 3 1]
 [0 4 2 0 0]]


In [182]:
arr = np.random.rand(3,4)

# 7. Manipulate an Array

### transpose an array

In [183]:
# the following methods return a copy
print(arr.T)
# or
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.1346135  0.70477855 0.04061612]
 [0.16555997 0.34951853 0.64582252]
 [0.61268228 0.27742396 0.03869959]
 [0.23878341 0.99891841 0.76021026]]
[[0.1346135  0.70477855 0.04061612]
 [0.16555997 0.34951853 0.64582252]
 [0.61268228 0.27742396 0.03869959]
 [0.23878341 0.99891841 0.76021026]]
[[0.1346135  0.70477855 0.04061612]
 [0.16555997 0.34951853 0.64582252]
 [0.61268228 0.27742396 0.03869959]
 [0.23878341 0.99891841 0.76021026]]


### transpose of a high dimensional array with specified order of axes

In [184]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [185]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [186]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.1346135 , 0.16555997, 0.61268228, 0.23878341, 0.70477855,
        0.34951853],
       [0.27742396, 0.99891841, 0.04061612, 0.64582252, 0.03869959,
        0.76021026]])

In [187]:
# change the shape of an array in place
arr.resize((2,6))

### flatten an array

In [188]:
# return a copy
arr.flatten()

array([0.1346135 , 0.16555997, 0.61268228, 0.23878341, 0.70477855,
       0.34951853, 0.27742396, 0.99891841, 0.04061612, 0.64582252,
       0.03869959, 0.76021026])

In [190]:
# return a view
# change any element in the view will change the initial array
x = arr.ravel()
x

array([0.1346135 , 0.16555997, 0.61268228, 0.23878341, 0.70477855,
       0.34951853, 0.27742396, 0.99891841, 0.04061612, 0.64582252,
       0.03869959, 0.76021026])

In [191]:
x[0] = 100
arr

array([[1.00000000e+02, 1.65559971e-01, 6.12682283e-01, 2.38783406e-01,
        7.04778548e-01, 3.49518527e-01],
       [2.77423960e-01, 9.98918406e-01, 4.06161246e-02, 6.45822522e-01,
        3.86995850e-02, 7.60210258e-01]])

### append elements to an array

In [192]:
arr = np.array([1,2,3])

In [193]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)
print(arr1)

[1 2 3 4]


In [194]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [196]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)
print(arr3)

[100   1   2   3]


In [197]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])
print(arr3)

[1 2 3 1 2 3]


### delete elements from an array

In [198]:
# remove the element at position 0
arr4 = np.delete(arr, 0)
print(arr4)

[2 3]


In [205]:
arrr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arrr = np.delete(arrr , [0,0])
arrr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [206]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])
print(arr4)

[2]


### copy an array

In [207]:
arr = np.array([1,2,3])

In [208]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or
arr1 = arr.copy()
# or
arr1 = np.array(arr, copy=True)

# 8. Combine & Split an Array

In [209]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### ```np.concatenate((a, b), axis=0)```

In [210]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [211]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))```
### ```np.r_[a, b]```

In [212]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [213]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [214]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [215]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


# 9. Set Operations

### select the unique elements from an array

In [219]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [220]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


### compute the intersection & union of two arrays

In [221]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [222]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [223]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### compute whether each element of an array is contained in another

In [224]:
print(np.in1d(arr1, arr2))

[False False  True  True  True]


In [226]:
# preserve the shape of the array in the output, if the array is of higher dimensions
print(np.isin(arr1, arr2))

[False False  True  True  True]


### compute the elements in an array that are not in another

In [227]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute the elements in either of two arrays, but not both

In [228]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


# 10. Linear Algebra

In [229]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [230]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[1.14593774 1.40904881 1.09469282 0.80214023 1.46232661]
 [1.09212873 1.19025398 0.81989156 0.78837689 1.24361687]
 [1.38431945 1.50010783 1.03060088 1.18603049 1.57122838]
 [0.67805148 0.98690735 0.81952501 0.6025586  1.02676732]
 [1.24986169 1.64054587 1.28637831 0.99915198 1.68841141]]
[[1.14593774 1.40904881 1.09469282 0.80214023 1.46232661]
 [1.09212873 1.19025398 0.81989156 0.78837689 1.24361687]
 [1.38431945 1.50010783 1.03060088 1.18603049 1.57122838]
 [0.67805148 0.98690735 0.81952501 0.6025586  1.02676732]
 [1.24986169 1.64054587 1.28637831 0.99915198 1.68841141]]
[[1.14593774 1.40904881 1.09469282 0.80214023 1.46232661]
 [1.09212873 1.19025398 0.81989156 0.78837689 1.24361687]
 [1.38431945 1.50010783 1.03060088 1.18603049 1.57122838]
 [0.67805148 0.98690735 0.81952501 0.6025586  1.02676732]
 [1.24986169 1.64054587 1.28637831 0.99915198 1.68841141]]


### singular value decomposition (SVD)

In [231]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.54818591 -0.06892406 -0.09088782 -0.50439662 -0.65731662]
 [-0.26988968  0.17282672 -0.53694001  0.72907915 -0.27826157]
 [-0.31912442  0.10730484  0.83290649  0.4046519  -0.17078904]
 [-0.52462782  0.62917001 -0.07717698 -0.19669933  0.53316399]
 [-0.49957685 -0.74700145 -0.06119903  0.10767476  0.42079999]]
[3.02499183 0.8007945  0.61800127 0.32613841 0.20704867]
[[-0.36504402 -0.49652615 -0.60603533 -0.27095889 -0.42368279]
 [-0.40222904  0.26546285 -0.01958426 -0.70779347  0.51612608]
 [-0.35410117  0.13484243  0.6418895  -0.22384793 -0.627933  ]
 [ 0.23374045 -0.78603607  0.44596965 -0.25933555  0.24772736]
 [-0.72452221 -0.2166935   0.14637819  0.55519984  0.3137484 ]]


### compute eigen values

In [232]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.53011269+0.j          0.51351236+0.j         -0.69444519+0.j
 -0.19389371+0.14234167j -0.19389371-0.14234167j]


### eigen value decomposition

In [234]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(" ============================================= ")
print(v)    # eigen vectors

[ 2.91527691+0.j         -0.54886909+0.j          0.17458007+0.28824091j
  0.17458007-0.28824091j  0.08782653+0.j        ]
[[-0.49910137+0.j          0.28299949+0.j          0.13375034+0.12369484j
   0.13375034-0.12369484j  0.28787418+0.j        ]
 [-0.34725241+0.j          0.38126685+0.j         -0.72007774+0.j
  -0.72007774-0.j         -0.62429124+0.j        ]
 [-0.3037686 +0.j         -0.71659418+0.j         -0.09702574+0.40370471j
  -0.09702574-0.40370471j -0.16913407+0.j        ]
 [-0.45026976+0.j          0.46375834+0.j          0.00680983+0.061157j
   0.00680983-0.061157j   -0.52835413+0.j        ]
 [-0.57904695+0.j         -0.21440116+0.j          0.26922286-0.44681036j
   0.26922286+0.44681036j  0.4686411 +0.j        ]]


### compute the trace & determinant

In [235]:
# notice this is not a function in linalg!!!
print(np.trace(arr))#calculates the sum of the diagonal elements of a 2D array (or matrix).

2.803394491994699


In [237]:
print(np.linalg.det(arr))#The determinant of the matrix, which is a scalar value.

-0.01595892402301516


### calculate the inverse/psedo-inverse of a matrix

In [238]:
arr = np.random.rand(5,5)

In [239]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[-0.34719027  0.64284161 -0.91239353 -1.63777927  1.56161703]
 [ 1.22004304  0.143929   -1.85211047  0.73782908  0.81687265]
 [-0.47335926  1.98742713  2.75239879 -0.4060076  -3.713789  ]
 [ 0.34832715 -0.29802914  1.69058232 -0.14867902 -1.14491003]
 [-1.33611739 -0.92206644  1.30818369  1.18036715  0.24086515]]


### solve a linear system

In [240]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[-0.54171957  2.98724918 -8.43428403 -1.49525041  6.67009514]
